[build-system]
requires = ["wheel", "setuptools"]
build-backend = "setuptools.build_meta"


[tool.black]
exclude = '''
( __pycache__
| ^/.tox
| ^/versioneer.py
| ^/src/debugpy/_vendored
| ^/src/debugpy/_version.py
)
'''
